### ISSUE TITLE
本地运行出现错误 bug

### ISSUE THREAD

**Issue by frank11311** [Guovin/TV#335]
情况：
本地运行FOFA扫描出现错误，同样的配置GitHub托管运行没有问题

错误提示：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tkinter_ui\tkinter_ui.py", line 112, in run_loop
  File "asyncio\base_events.py", line 608, in run_until_complete
  File "tkinter_ui\tkinter_ui.py", line 98, in run_update
  File "main.py", line 222, in start
  File "main.py", line 144, in main
  File "main.py", line 111, in visit_page
  File "updates\fofa\request.py", line 159, in get_channels_by_fofa
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "updates\fofa\request.py", line 142, in process_fofa_channels
UnboundLocalError: local variable 'driver' referenced before assignment

配置文件：
[Settings]
open_update = True
open_use_old_result = True
source_file = config/demo.txt
final_file = output/result.txt
open_online_search = True
online_search_page_num = 3
urls_limit = 15
open_keep_all = False
open_sort = True
open_ffmpeg = True
response_time_weight = 0.5
resolution_weight = 0.5
recent_days = 30
ipv_type = all
domain_blacklist = epg.pw,skype.serv00.net
open_m3u_result = True
url_keywords_blacklist = 
open_subscribe = False
subscribe_urls = https://raw.githubusercontent.com/frank11311/CTVLive/main/live.txt,https://raw.githubusercontent.com/PizazzGY/TVBox/main/live.txt
open_multicast = True
open_multicast_tonkiang = True
open_multicast_fofa = True
multicast_region_list = 上海
multicast_page_num = 3
open_proxy = False
open_driver = True
open_hotel = True
open_hotel_tonkiang = False
open_hotel_fofa = True
hotel_region_list = 上海
hotel_page_num = 3

截图：
![QQ图片20240922150236](https://github.com/user-attachments/assets/4698304f-0809-4220-9cba-fc6f8cda0b19)

**Comment by Guovin** [comment]
开启浏览器模式请确保系统已安装谷歌浏览器

**Comment by frank11311** [comment]
已经安装了Chrome最新版本

**Comment by frank11311** [comment]
反而关闭浏览器模式，能正常运行

**Comment by Guovin** [comment]
已修复，请更新v1.4.7
