### ISSUE TITLE
docker容器闪退

### ISSUE THREAD

**Issue by snowdream** [Guovin/TV#438]
在爱快 docker 上运行tv-driver，运行命令类似。

```
docker run -v /etc/docker/config:/tv-driver/config -v /etc/docker/output:/tv-driver/output -d -p 8000:8000 guovern/tv-driver
```

闪退，日志如下：

```
cron: unrecognized service
/tv-driver/updates/fofa/request.py:73: TqdmMonitorWarning: tqdm:disabling monitor support (monitor_interval = 0) due to:
can't start new thread
pbar = tqdm_asyncio(
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]Traceback (most recent call last):
File "/tv-driver/main.py", line 273, in <module>
scheduled_task()
File "/tv-driver/main.py", line 259, in scheduled_task
loop.run_until_complete(update_source.start())
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/tv-driver/main.py", line 244, in start
await self.main()
File "/tv-driver/main.py", line 148, in main
await self.visit_page(channel_names)
File "/tv-driver/main.py", line 117, in visit_page
setattr(self, result_attr, await task)
File "/tv-driver/updates/fofa/request.py", line 155, in get_channels_by_fofa
futures = [
File "/tv-driver/updates/fofa/request.py", line 156, in <listcomp>
executor.submit(process_fofa_channels, fofa_url) for fofa_url in fofa_urls
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
self._adjust_thread_count()
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
t.start()
File "/usr/local/lib/python3.8/threading.py", line 852, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/tv-driver-D9SmWF1i/lib/python3.8/site-packages/tqdm/_monitor.py", line 44, in exit
self.join()
File "/usr/local/lib/python3.8/threading.py", line 1006, in join
raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]
/tv_entrypoint.sh: line 15: gunicorn: command not found
cron: unrecognized service
/tv-driver/updates/fofa/request.py:73: TqdmMonitorWarning: tqdm:disabling monitor support (monitor_interval = 0) due to:
can't start new thread
pbar = tqdm_asyncio(
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]Traceback (most recent call last):
File "/tv-driver/main.py", line 273, in <module>
scheduled_task()
File "/tv-driver/main.py", line 259, in scheduled_task
loop.run_until_complete(update_source.start())
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/tv-driver/main.py", line 244, in start
await self.main()
File "/tv-driver/main.py", line 148, in main
await self.visit_page(channel_names)
File "/tv-driver/main.py", line 117, in visit_page
setattr(self, result_attr, await task)
File "/tv-driver/updates/fofa/request.py", line 155, in get_channels_by_fofa
futures = [
File "/tv-driver/updates/fofa/request.py", line 156, in <listcomp>
executor.submit(process_fofa_channels, fofa_url) for fofa_url in fofa_urls
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
self._adjust_thread_count()
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
t.start()
File "/usr/local/lib/python3.8/threading.py", line 852, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/tv-driver-D9SmWF1i/lib/python3.8/site-packages/tqdm/_monitor.py", line 44, in exit
self.join()
File "/usr/local/lib/python3.8/threading.py", line 1006, in join
raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]
/tv_entrypoint.sh: line 15: gunicorn: command not found
cron: unrecognized service
/tv-driver/updates/fofa/request.py:73: TqdmMonitorWarning: tqdm:disabling monitor support (monitor_interval = 0) due to:
can't start new thread
pbar = tqdm_asyncio(
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]Traceback (most recent call last):
File "/tv-driver/main.py", line 273, in <module>
scheduled_task()
File "/tv-driver/main.py", line 259, in scheduled_task
loop.run_until_complete(update_source.start())
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/tv-driver/main.py", line 244, in start
await self.main()
File "/tv-driver/main.py", line 148, in main
await self.visit_page(channel_names)
File "/tv-driver/main.py", line 117, in visit_page
setattr(self, result_attr, await task)
File "/tv-driver/updates/fofa/request.py", line 155, in get_channels_by_fofa
futures = [
File "/tv-driver/updates/fofa/request.py", line 156, in <listcomp>
executor.submit(process_fofa_channels, fofa_url) for fofa_url in fofa_urls
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
self._adjust_thread_count()
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
t.start()
File "/usr/local/lib/python3.8/threading.py", line 852, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/tv-driver-D9SmWF1i/lib/python3.8/site-packages/tqdm/_monitor.py", line 44, in exit
self.join()
File "/usr/local/lib/python3.8/threading.py", line 1006, in join
raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
Processing fofa for hotel: 0% 0/45 [00:00<?, ?it/s]
/tv_entrypoint.sh: line 15: gunicorn: command not found
```

**Comment by Guovin** [comment]
看起来是docker无法支持创建多线程的原因，检查下你的docker版本、容器系统版本信息，以便我分析解决

**Comment by snowdream** [comment]
爱快系统上的 Docker 插件，没法判断版本：
https://www.ikuai8.com/index.php?option=com_content&view=article&id=679&Itemid=522

拉取的是最新镜像：guovern/tv-driver:latest

**Comment by sztuxp** [comment]
甲骨文的arm机器昨天还好的，今天开始闪退，我用watchtower 自动更新最新版本

**Comment by Guovin** [comment]
> 甲骨文的arm机器昨天还好的，今天开始闪退，我用watchtower 自动更新最新版本

最近没有更新镜像，检查一下报错日志
