### ISSUE TITLE
程序运行时报错，然后就不动了，请问这是怎么回事？

### ISSUE THREAD

**Issue by myyfan** [Guovin/TV#527]
Exception in thread Thread-3362:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tkinter_ui\tkinter_ui.py", line 119, in run_loop
  File "asyncio\base_events.py", line 608, in run_until_complete
  File "tkinter_ui\tkinter_ui.py", line 105, in run_update
  File "main.py", line 239, in start
  File "main.py", line 173, in main
  File "utils\channel.py", line 707, in process_sort_channel_list
UnboundLocalError: local variable 'cache_key' referenced before assignment

错误提示如上

**Comment by Guovin** [comment]
我上传了修复版本，你下载再试试
